use_frameworks!

target 'Collectionist_Example' do

	pod 'Layitout', :git => 'https://github.com/buscarini/layitout.git', :branch => 'feature/Swift3'
	pod 'Miscel', :git => 'https://github.com/buscarini/miscel.git', :branch => 'feature/Swift3'
	
	pod 'Collectionist', :path => '../'

	target 'Collectionist_Tests' do
		inherit! :search_paths

    
	end
end
